# ruff: noqa: F401
"""Extended tests for src/parse_olm.py — targeting uncovered lines."""

from __future__ import annotations

import base64
import zipfile
from pathlib import Path

import pytest
from lxml import etree

from src.olm_xml_helpers import (
    _detect_namespace,
    _extract_attachment_contents,
    _extract_attachment_field,
    _extract_html_body,
    _find,
    _find_text,
)
from src.parse_olm import (
    _NS_OUTLOOK,
    Email,
    _parse_email_xml,
    parse_olm,
)
from src.parse_olm_normalization import BODY_NORMALIZATION_VERSION

# ── Email.uid fallback (lines 98-99) ─────────────────────────


class TestCleanBodyHtmlInBodyText:
    def test_clean_body_html_in_body_text_field(self):
        """When body_text contains HTML, clean_body strips HTML tags."""
        email = Email(
            message_id="<m@test>",
            subject="Test",
            sender_name="",
            sender_email="",
            to=[],
            cc=[],
            bcc=[],
            date="",
            body_text="<html><body><p>Hello</p></body></html>",
            body_html="",
            folder="Inbox",
            has_attachments=False,
        )
        result = email.clean_body
        assert "Hello" in result
        assert "<html>" not in result
        assert "<p>" not in result

    def test_clean_body_prefers_cleaner_html_representation(self):
        """Noisy autogenerated plain text should not always beat cleaner HTML."""
        email = Email(
            message_id="<m@test>",
            subject="Test",
            sender_name="",
            sender_email="",
            to=[],
            cc=[],
            bcc=[],
            date="",
            body_text=(
                "Visible summary.\n\n"
                "From: Alice <alice@example.com>\n"
                "Sent: Monday, January 1, 2025 10:00 AM\n"
                "To: Bob <bob@example.com>\n"
                "Subject: RE: Test\n\n"
                "> Prior content"
            ),
            body_html="<div><p>Visible summary.</p></div>",
            folder="Inbox",
            has_attachments=False,
        )
        assert email.clean_body == "Visible summary."
        assert email.clean_body_source == "body_html"
        assert email.body_normalization_version == BODY_NORMALIZATION_VERSION

    def test_clean_body_tracks_html_in_body_text_source(self):
        email = Email(
            message_id="<m@test>",
            subject="Test",
            sender_name="",
            sender_email="",
            to=[],
            cc=[],
            bcc=[],
            date="",
            body_text="<html><body><p>Hello</p></body></html>",
            body_html="",
            folder="Inbox",
            has_attachments=False,
        )
        assert email.clean_body == "Hello"
        assert email.clean_body_source == "body_text_html"

    def test_clean_body_strips_mobile_signature_in_normalized_body(self):
        email = Email(
            message_id="<m@test>",
            subject="Test",
            sender_name="",
            sender_email="",
            to=[],
            cc=[],
            bcc=[],
            date="",
            body_text="See you tomorrow.\n\nSent from my iPhone",
            body_html="",
            folder="Inbox",
            has_attachments=False,
        )
        assert email.clean_body == "See you tomorrow."
        assert email.clean_body_source == "body_text"
        assert email.body_normalization_version == BODY_NORMALIZATION_VERSION

    def test_clean_body_strips_closing_signature_in_normalized_body(self):
        email = Email(
            message_id="<m@test>",
            subject="Test",
            sender_name="",
            sender_email="",
            to=[],
            cc=[],
            bcc=[],
            date="",
            body_text="I'll handle it.\n\nBest regards,\nAlice Smith\nManager",
            body_html="",
            folder="Inbox",
            has_attachments=False,
        )
        assert email.clean_body == "I'll handle it."

    def test_clean_body_keeps_regular_prose_without_signature_marker(self):
        email = Email(
            message_id="<m@test>",
            subject="Test",
            sender_name="",
            sender_email="",
            to=[],
            cc=[],
            bcc=[],
            date="",
            body_text="Just a regular email without a signature.",
            body_html="",
            folder="Inbox",
            has_attachments=False,
        )
        assert email.clean_body == "Just a regular email without a signature."

    def test_clean_body_strips_multiline_legal_disclaimer_tail(self):
        email = Email(
            message_id="<m@test>",
            subject="Test",
            sender_name="",
            sender_email="",
            to=[],
            cc=[],
            bcc=[],
            date="",
            body_text=(
                "Action items are attached.\n\n"
                "This email and any attachments are confidential and intended only for the named recipient.\n"
                "If you are not the intended recipient, please notify the sender and delete this email.\n"
                "Any unauthorized review, use, disclosure, or distribution is prohibited."
            ),
            body_html="",
            folder="Inbox",
            has_attachments=False,
        )
        assert email.clean_body == "Action items are attached."
        assert email.body_normalization_version == BODY_NORMALIZATION_VERSION

    def test_clean_body_keeps_single_line_confidentiality_notice(self):
        email = Email(
            message_id="<m@test>",
            subject="Test",
            sender_name="",
            sender_email="",
            to=[],
            cc=[],
            bcc=[],
            date="",
            body_text=("Status report attached.\n\nConfidentiality notice: This email may contain privileged information."),
            body_html="",
            folder="Inbox",
            has_attachments=False,
        )
        assert "Confidentiality notice" in email.clean_body

    def test_clean_body_strips_reply_quote_tail_before_persistence(self):
        email = Email(
            message_id="<m@test>",
            subject="RE: Project update",
            sender_name="",
            sender_email="",
            to=[],
            cc=[],
            bcc=[],
            date="",
            body_text=(
                "Latest status is below.\n\n----- Original Message -----\nFrom: Alice\nSubject: Project update\n\nPrior body."
            ),
            body_html="",
            folder="Inbox",
            has_attachments=False,
        )
        assert email.email_type == "reply"
        assert email.clean_body == "Latest status is below."
        assert email.body_normalization_version == BODY_NORMALIZATION_VERSION

    def test_clean_body_keeps_separator_text_for_original_email(self):
        email = Email(
            message_id="<m@test>",
            subject="Project archive note",
            sender_name="",
            sender_email="",
            to=[],
            cc=[],
            bcc=[],
            date="",
            body_text=("Reference below.\n\n----- Original Message -----\nThis separator is part of the saved note."),
            body_html="",
            folder="Inbox",
            has_attachments=False,
        )
        assert email.email_type == "original"
        assert "----- Original Message -----" in email.clean_body

    def test_clean_body_strips_reply_header_only_tail_before_persistence(self):
        email = Email(
            message_id="<m@test>",
            subject="RE: Status",
            sender_name="",
            sender_email="",
            to=[],
            cc=[],
            bcc=[],
            date="",
            body_text=(
                "Latest answer.\n\n"
                "From: Alice <alice@example.com>\n"
                "Sent: Monday, January 1, 2025 10:00 AM\n"
                "To: Bob <bob@example.com>\n"
                "Subject: Status"
            ),
            body_html="",
            folder="Inbox",
            has_attachments=False,
        )
        assert email.email_type == "reply"
        assert email.clean_body == "Latest answer."
        assert email.body_normalization_version == BODY_NORMALIZATION_VERSION

    def test_clean_body_strips_reply_header_block_after_intro_before_persistence(self):
        email = Email(
            message_id="<m@test>",
            subject="FW: Status",
            sender_name="",
            sender_email="",
            to=[],
            cc=[],
            bcc=[],
            date="",
            body_text=(
                "Please see below.\n\n"
                "From: Alice <alice@example.com>\n"
                "Sent: Monday, January 1, 2025 10:00 AM\n"
                "To: Bob <bob@example.com>\n"
                "Subject: Status\n\n"
                "Prior body content."
            ),
            body_html="",
            folder="Inbox",
            has_attachments=False,
        )
        assert email.email_type == "forward"
        assert email.clean_body == "Please see below."

    def test_clean_body_strips_html_reply_header_block_after_intro(self):
        email = Email(
            message_id="<m@test>",
            subject="AW: Status",
            sender_name="",
            sender_email="",
            to=[],
            cc=[],
            bcc=[],
            date="",
            body_text="",
            body_html=(
                "<div>Aktueller Stand unten.</div>"
                "<div><br></div>"
                "<div>Von: Alice &lt;alice@example.com&gt;</div>"
                "<div>Gesendet: Montag, 1. Januar 2025 10:00</div>"
                "<div>An: Bob &lt;bob@example.com&gt;</div>"
                "<div>Betreff: Status</div>"
                "<div><br></div>"
                "<div>Vorheriger Inhalt.</div>"
            ),
            folder="Inbox",
            has_attachments=False,
        )
        assert email.email_type == "reply"
        assert email.clean_body == "Aktueller Stand unten."
        assert email.clean_body_source == "body_html"

    def test_clean_body_keeps_headerish_tail_for_original_email(self):
        email = Email(
            message_id="<m@test>",
            subject="Archive note",
            sender_name="",
            sender_email="",
            to=[],
            cc=[],
            bcc=[],
            date="",
            body_text=(
                "Reference block below.\n\n"
                "From: Alice <alice@example.com>\n"
                "Sent: Monday, January 1, 2025 10:00 AM\n"
                "To: Bob <bob@example.com>\n"
                "Subject: Status"
            ),
            body_html="",
            folder="Inbox",
            has_attachments=False,
        )
        assert email.email_type == "original"
        assert "From: Alice <alice@example.com>" in email.clean_body

    def test_clean_body_strips_german_reply_header_tail_before_persistence(self):
        email = Email(
            message_id="<m@test>",
            subject="AW: Status",
            sender_name="",
            sender_email="",
            to=[],
            cc=[],
            bcc=[],
            date="",
            body_text=(
                "Aktueller Stand unten.\n\n"
                "Von: Alice <alice@example.com>\n"
                "Gesendet: Montag, 1. Januar 2025 10:00\n"
                "An: Bob <bob@example.com>\n"
                "Betreff: Status"
            ),
            body_html="",
            folder="Inbox",
            has_attachments=False,
        )
        assert email.email_type == "reply"
        assert email.clean_body == "Aktueller Stand unten."
        assert email.body_normalization_version == BODY_NORMALIZATION_VERSION

    def test_clean_body_strips_reply_header_tail_after_signature_prelude(self):
        email = Email(
            message_id="<m@test>",
            subject="AW: Status",
            sender_name="",
            sender_email="",
            to=[],
            cc=[],
            bcc=[],
            date="",
            body_text=(
                "Aktueller Stand unten.\n\n"
                "Viele Grüße\nAlice\n\n"
                "Von: Bob <bob@example.com>\n"
                "Gesendet: Montag, 1. Januar 2025 10:00\n"
                "An: Alice <alice@example.com>\n"
                "Betreff: Status\n\n"
                "Vorheriger Inhalt."
            ),
            body_html="",
            folder="Inbox",
            has_attachments=False,
        )
        assert email.clean_body == "Aktueller Stand unten."

    def test_clean_body_strips_reply_header_tail_from_original_nachricht_separator(self):
        email = Email(
            message_id="<m@test>",
            subject="AW: Status",
            sender_name="",
            sender_email="",
            to=[],
            cc=[],
            bcc=[],
            date="",
            body_text=(
                "Danke, erledigt.\n\n"
                "Prof. Beispiel\n"
                "Leitung IT\n\n"
                "-----Original-Nachricht-----\n"
                "Von: Alice <alice@example.com>\n"
                "Gesendet: Montag, 1. Januar 2025 10:00\n"
                "An: Bob <bob@example.com>\n"
                "Betreff: Status\n\n"
                "Voriger Inhalt."
            ),
            body_html="",
            folder="Inbox",
            has_attachments=False,
        )
        assert email.clean_body == "Danke, erledigt.\n\nProf. Beispiel\nLeitung IT"

    def test_clean_body_strips_reply_header_tail_after_long_signature_prelude(self):
        email = Email(
            message_id="<m@test>",
            subject="RE: Status",
            sender_name="",
            sender_email="",
            to=[],
            cc=[],
            bcc=[],
            date="",
            body_text=(
                "Erledigt.\n\n"
                "Dr. Alice Example\n"
                "Leitung IT\n"
                "Beispielweg 10\n"
                "12345 Musterstadt\n\n"
                "Von: Bob <bob@example.com>\n"
                "Gesendet: Montag, 1. Januar 2025 10:00\n"
                "An: Alice <alice@example.com>\n"
                "Betreff: Status\n\n"
                "Voriger Inhalt."
            ),
            body_html="",
            folder="Inbox",
            has_attachments=False,
        )
        assert email.clean_body == ("Erledigt.\n\nDr. Alice Example\nLeitung IT\nBeispielweg 10\n12345 Musterstadt")

    def test_clean_body_keeps_german_headerish_tail_for_original_email(self):
        email = Email(
            message_id="<m@test>",
            subject="Archivnotiz",
            sender_name="",
            sender_email="",
            to=[],
            cc=[],
            bcc=[],
            date="",
            body_text=(
                "Referenzblock unten.\n\n"
                "Von: Alice <alice@example.com>\n"
                "Gesendet: Montag, 1. Januar 2025 10:00\n"
                "An: Bob <bob@example.com>\n"
                "Betreff: Status"
            ),
            body_html="",
            folder="Inbox",
            has_attachments=False,
        )
        assert email.email_type == "original"
        assert "Von: Alice <alice@example.com>" in email.clean_body

    def test_clean_body_strips_portuguese_reply_header_tail_before_persistence(self):
        email = Email(
            message_id="<m@test>",
            subject="RE: Status",
            sender_name="",
            sender_email="",
            to=[],
            cc=[],
            bcc=[],
            date="",
            body_text=(
                "Resposta atual.\n\n"
                "De: Alice <alice@example.com>\n"
                "Enviado: segunda-feira, 1 de janeiro de 2025 10:00\n"
                "Para: Bob <bob@example.com>\n"
                "Assunto: Status"
            ),
            body_html="",
            folder="Inbox",
            has_attachments=False,
        )
        assert email.email_type == "reply"
        assert email.clean_body == "Resposta atual."
        assert email.body_normalization_version == BODY_NORMALIZATION_VERSION

    def test_clean_body_strips_polish_reply_header_tail_before_persistence(self):
        email = Email(
            message_id="<m@test>",
            subject="RE: Status",
            sender_name="",
            sender_email="",
            to=[],
            cc=[],
            bcc=[],
            date="",
            body_text=(
                "Aktualna odpowiedz.\n\n"
                "Od: Alice <alice@example.com>\n"
                "Wyslano: poniedzialek, 1 stycznia 2025 10:00\n"
                "Do: Bob <bob@example.com>\n"
                "Temat: Status"
            ),
            body_html="",
            folder="Inbox",
            has_attachments=False,
        )
        assert email.email_type == "reply"
        assert email.clean_body == "Aktualna odpowiedz."
        assert email.body_normalization_version == BODY_NORMALIZATION_VERSION

    def test_clean_body_strips_get_outlook_ios_footer_in_normalized_body(self):
        email = Email(
            message_id="<m@test>",
            subject="Test",
            sender_name="",
            sender_email="",
            to=[],
            cc=[],
            bcc=[],
            date="",
            body_text="Please see the attached file.\n\nGet Outlook for iOS",
            body_html="",
            folder="Inbox",
            has_attachments=False,
        )
        assert email.clean_body == "Please see the attached file."
        assert email.body_normalization_version == BODY_NORMALIZATION_VERSION

    def test_clean_body_strips_leading_forward_header_block_and_keeps_forwarded_content(self):
        email = Email(
            message_id="<m@test>",
            subject="FW: Status",
            sender_name="",
            sender_email="",
            to=[],
            cc=[],
            bcc=[],
            date="",
            body_text=(
                "From: Alice <alice@example.com>\n"
                "Sent: Monday, January 1, 2025 10:00 AM\n"
                "To: Bob <bob@example.com>\n"
                "Subject: Status\n\n"
                "Forwarded content starts here."
            ),
            body_html="",
            folder="Inbox",
            has_attachments=False,
        )
        assert email.clean_body == "Forwarded content starts here."

    def test_clean_body_strips_leading_forward_header_block_after_outlook_separator(self):
        email = Email(
            message_id="<m@test>",
            subject="FW: Status",
            sender_name="",
            sender_email="",
            to=[],
            cc=[],
            bcc=[],
            date="",
            body_text=(
                "________________________________\n"
                "From: Alice <alice@example.com>\n"
                "Sent: Monday, January 1, 2025 10:00 AM\n"
                "To: Bob <bob@example.com>\n"
                "Subject: Status\n\n"
                "Forwarded content starts here."
            ),
            body_html="",
            folder="Inbox",
            has_attachments=False,
        )
        assert email.clean_body == "Forwarded content starts here."
