# ruff: noqa: F401
from ._parse_olm_cases import (
    test_clean_text_collapses_blank_lines,
    test_clean_text_preserves_leading_indentation,
    test_clean_text_strips_trailing_whitespace,
    test_extract_html_body_mixed_content,
    test_extract_html_body_pure_text,
    test_extract_html_body_with_child_elements,
    test_extract_name_from_header_escaped_quotes,
    test_extract_name_from_header_unquoted,
    test_html_to_text_preserves_blockquote,
    test_html_to_text_preserves_headings,
    test_html_to_text_preserves_links,
    test_html_to_text_preserves_lists,
    test_html_to_text_preserves_tables,
    test_normalize_date_empty,
    test_normalize_date_iso_passthrough,
    test_normalize_date_rfc2822_to_iso,
    test_normalize_date_unparseable,
    test_parse_references_bare_only,
    test_parse_references_mixed_bracketed_and_bare,
    test_parse_references_no_duplicates,
    test_sender_email_normalized_lowercase,
)
