version: 1
github-actions: core-build-out
split-large-regression-s: core-build-out
ruff: publication
hugo: publication
github-actions: publication
separate-dev-and-release: publication
ruff: maintenance
align-ignore-rules-with-: maintenance
# forced-ruff-9:maintenance
# forced-ruff-10:maintenance
# forced-ruff-11:maintenance
