version: 1
github-actions: core-build-out
split-large-regression-s: core-build-out
ruff: publication
hugo: publication
github-actions: publication
separate-dev-and-release: publication
ruff: maintenance
align-ignore-rules-with-: maintenance
# forced-ruff-9:maintenance
# forced-ruff-10:maintenance
# forced-ruff-11:maintenance
clean-temporary-review-a: maintenance
add-snapshot-coverage-fo: maintenance
github-actions: maintenance
# forced-github-actions-15:maintenance
# forced-github-actions-16:maintenance
# forced-ruff-17:maintenance
# forced-ruff-18:maintenance
# forced-ruff-19:maintenance
# forced-github-actions-20:maintenance
# forced-ruff-21:maintenance
# forced-github-actions-22:maintenance
