"""Pydantic input models for MCP tools.

All MCP tool parameter models are defined in sub-modules and re-exported here
so that ``from src.mcp_models import SomeModel`` continues to work everywhere.

Sub-modules:
- ``mcp_models_base``: Base classes (StrictInput, PlainInput, DateRangeInput).
- ``mcp_models_search``: Search, browse, export, scan, and ingestion inputs.
- ``mcp_models_evidence``: Evidence management, chain of custody, dossier inputs.
- ``mcp_models_analysis``: Network, entity, thread, temporal, quality, and report inputs.
"""

from .mcp_models_analysis import (
    ActionItemsInput,
    AdverseActionInput,
    BehavioralCaseScopeInput,
    BehavioralOrgContextInput,
    CasePartyInput,
    CoordinatedTimingInput,
    DecisionsInput,
    DependencyRelationInput,
    EmailAdminInput,
    EmailAttachmentsInput,
    EmailClustersInput,
    EmailContactsInput,
    EmailQualityInput,
    EmailReportInput,
    EmailTemporalInput,
    EmailThreadLookupInput,
    EmailTopicsInput,
    EntityNetworkInput,
    EntitySearchInput,
    EntityTimelineInput,
    InstitutionalActorInput,
    ListEntitiesInput,
    NetworkAnalysisInput,
    RelationshipPathsInput,
    RelationshipSummaryInput,
    ReportingLineInput,
    RoleFactInput,
    SharedRecipientsInput,
    ThreadSummaryInput,
    TriggerEventInput,
    VulnerabilityContextInput,
)
from .mcp_models_base import (
    DateRangeInput,
    PlainInput,
    StrictInput,
    _validate_output_path,
)
from .mcp_models_case_analysis import (
    CaseChatExportInput,
    CaseChatLogEntryInput,
    EmailCaseAnalysisInput,
    EmailCaseExecuteAllWavesInput,
    EmailCaseExecuteWaveInput,
    EmailCaseFullPackInput,
    EmailCaseGatherEvidenceInput,
    EmailCasePromptPreflightInput,
    EmailLegalSupportExportInput,
    EmailLegalSupportInput,
    MatterArtifactInput,
    MatterManifestInput,
)
from .mcp_models_evidence import (
    CustodyChainInput,
    EmailDossierInput,
    EmailProvenanceInput,
    EvidenceAddBatchInput,
    EvidenceAddInput,
    EvidenceExportInput,
    EvidenceGetInput,
    EvidenceOverviewInput,
    EvidenceProvenanceInput,
    EvidenceQueryInput,
    EvidenceRemoveInput,
    EvidenceUpdateInput,
)
from .mcp_models_search import (
    BrowseInput,
    EmailAnswerContextInput,
    EmailDeepContextInput,
    EmailDiscoveryInput,
    EmailExportInput,
    EmailIngestInput,
    EmailScanInput,
    EmailSearchStructuredInput,
    EmailTriageInput,
    FindSimilarInput,
    ListSendersInput,
)

__all__ = [
    "ActionItemsInput",
    "AdverseActionInput",
    "BehavioralCaseScopeInput",
    "BehavioralOrgContextInput",
    "BrowseInput",
    "CaseChatExportInput",
    "CaseChatLogEntryInput",
    "CasePartyInput",
    "CoordinatedTimingInput",
    "CustodyChainInput",
    "DateRangeInput",
    "DecisionsInput",
    "DependencyRelationInput",
    "EmailAdminInput",
    "EmailAnswerContextInput",
    "EmailAttachmentsInput",
    "EmailCaseAnalysisInput",
    "EmailCaseExecuteAllWavesInput",
    "EmailCaseExecuteWaveInput",
    "EmailCaseFullPackInput",
    "EmailCaseGatherEvidenceInput",
    "EmailCasePromptPreflightInput",
    "EmailClustersInput",
    "EmailContactsInput",
    "EmailDeepContextInput",
    "EmailDiscoveryInput",
    "EmailDossierInput",
    "EmailExportInput",
    "EmailIngestInput",
    "EmailLegalSupportExportInput",
    "EmailLegalSupportInput",
    "EmailProvenanceInput",
    "EmailQualityInput",
    "EmailReportInput",
    "EmailScanInput",
    "EmailSearchStructuredInput",
    "EmailTemporalInput",
    "EmailThreadLookupInput",
    "EmailTopicsInput",
    "EmailTriageInput",
    "EntityNetworkInput",
    "EntitySearchInput",
    "EntityTimelineInput",
    "EvidenceAddBatchInput",
    "EvidenceAddInput",
    "EvidenceExportInput",
    "EvidenceGetInput",
    "EvidenceOverviewInput",
    "EvidenceProvenanceInput",
    "EvidenceQueryInput",
    "EvidenceRemoveInput",
    "EvidenceUpdateInput",
    "FindSimilarInput",
    "InstitutionalActorInput",
    "ListEntitiesInput",
    "ListSendersInput",
    "MatterArtifactInput",
    "MatterManifestInput",
    "NetworkAnalysisInput",
    "PlainInput",
    "RelationshipPathsInput",
    "RelationshipSummaryInput",
    "ReportingLineInput",
    "RoleFactInput",
    "SharedRecipientsInput",
    "StrictInput",
    "ThreadSummaryInput",
    "TriggerEventInput",
    "VulnerabilityContextInput",
    "_validate_output_path",
]
